name: selenium

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 6 * * *'  
  # Triggers the workflow on push or pull request events but only for the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      # Runs a single command using the runners shell
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7
           
      - name: Install Chinese Support
        run: |
          git pull
          sudo apt-get install language-pack-zh-han*
          sudo apt-get install ttf-mscorefonts-installer
          sudo apt-get install fontconfig
          LANG="zh_CN.UTF-8"
          cp HarmonyOS.ttf /usr/share/fonts/
          sudo chmod 644 /usr/share/fonts/HarmonyOS.ttf
          sudo mkfontscale
          sudo mkfontdir
          sudo fc-cache -fv
          
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
            && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
            && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
            && cd /tmp \
            && unzip chromedriver_linux64.zip \
            && rm -rf chromedriver_linux64.zip \
            && sudo mv chromedriver /usr/local/bin/chromedriver \
            && sudo chmod +x /usr/local/bin/chromedriver \
            && chromedriver --version
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt

      - name: 'ALL IN ONE'
        run: python ./main.py

      - name: 'DELETE DAYDEL FILES'
        run: python ./del.py

      - name: 'RELOAD DAYDEL FILES'
        run: python ./reload.py

      - name: Commit ALL IN ONE files
        run: |
          git config --local user.email "admin@icodeq.com"
          git config --local user.name "zkeq"
          git checkout --orphan latest_branch
          git add -A
          git commit -m "GitHub Actions Crawler ALL IN ONE at $(date +'%Y-%m-%d %H:%M:%S')"
          git branch -D master
          git branch -m master
         
      - name: Push changes
        uses:  ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          branch: ${{ github.ref }}
          force: true
